-- Create saving_terms table
CREATE TABLE saving_terms (
    term_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    term_type VARCHAR(30) NOT NULL UNIQUE,
    interest_rate DECIMAL(10, 4) NOT NULL,
    updated_at TIMESTAMP NULL,
    updated_by VARCHAR(100) NULL
);

-- Insert default interest rates
INSERT INTO saving_terms (term_type, interest_rate, updated_at) VALUES
('NON_TERM', 0.20, CURRENT_TIMESTAMP),
('ONE_MONTH', 3.20, CURRENT_TIMESTAMP),
('TWO_MONTHS', 3.40, CURRENT_TIMESTAMP),
('THREE_MONTHS', 3.60, CURRENT_TIMESTAMP),
('SIX_MONTHS', 4.80, CURRENT_TIMESTAMP),
('NINE_MONTHS', 5.00, CURRENT_TIMESTAMP),
('TWELVE_MONTHS', 5.50, CURRENT_TIMESTAMP),
('FIFTEEN_MONTHS', 5.80, CURRENT_TIMESTAMP),
('EIGHTEEN_MONTHS', 6.00, CURRENT_TIMESTAMP),
('TWENTY_FOUR_MONTHS', 6.40, CURRENT_TIMESTAMP),
('THIRTY_SIX_MONTHS', 6.80, CURRENT_TIMESTAMP);

